### ISSUE TITLE
跪求 Firefox 外掛套件版

### ISSUE THREAD

**Issue by SarsTW** [CindyLinz/Chrome-GreenifyFacebook#1]
餓死抬頭  XDD

**Comment by CindyLinz** [comment]
我還不會寫 Firefox 的 addon.. T_T 這要拜託其他大大....

雖然我是有想也點一點 Firefox addon 的技能, 因為新版的 Firefox 用起來好快好順, 不過不能預期能學多快 @@"

**Comment by evelynhung** [comment]
> 因為新版的 Firefox 用起來好快好順,

衝著這句話只好來發 PR.. #2  ❤️

**Comment by CindyLinz** [comment]
喔喔喔!!

**Comment by CindyLinz** [comment]
經過 @evelynhung 的指導, Firefox 版生出來了.. :D

public addon 還在審, 看說明好像是人工審查, 不知道會審多久 orz

目前 Queue Position: 108 of 109

可以先用 [private](https://github.com/CindyLinz/Chrome-GreenifyFacebook/tree/master/dist) 版的將就一下, 內容一樣, 只是 addon id 不一樣, 然後不會自動更新這樣...

**Comment by CindyLinz** [comment]
咦, 還沒審過的好像也可以自己開 [網址](https://addons.mozilla.org/en-US/firefox/addon/greenifyfacebook) 下載的樣子?

**Comment by CindyLinz** [comment]
看起來有得等了... ^^|
Queue Position: 106 of 114

**Comment by CindyLinz** [comment]
Approved 了 https://addons.mozilla.org/en-US/firefox/addon/greenifyfacebook/
