### ISSUE TITLE
Chrome  59.0.3071.115 ontline 選擇框

### ISSUE THREAD

**Issue by sexyoung** [CindyLinz/Chrome-GreenifyFacebook#3]
<img width="719" alt="2017-08-01 3 57 44" src="https://user-images.githubusercontent.com/1787867/28830342-04d0696c-7709-11e7-93ce-30956c3b3c2f.png">

**Comment by CindyLinz** [comment]
欸那你這問題還在嗎?

**Comment by sexyoung** [comment]
好像沒有了欸 酷
<img width="1222" alt="2017-08-02 11 52 11" src="https://user-images.githubusercontent.com/1787867/28882383-a6b0f27c-77dd-11e7-8b96-52c9affc8d08.png">

**Comment by CindyLinz** [comment]
好~~~ 那我 close issue 了 ^__^

**Comment by sexyoung** [comment]
感謝您

**Comment by sexyoung** [comment]
有空也用手機來玩玩我的好食相機
https://ingredient.shot.tw

**Comment by CindyLinz** [comment]
好~~~ :D
